apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah-simple
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: quay.io/buildah/stable:v1
      securityContext:
        privileged: true
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        set -e
        buildah bud --storage-driver=overlay -f ./Dockerfile -t $(params.IMAGE) .
        buildah push --tls-verify=false $(params.IMAGE)
