apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8-lint
spec:
  workspaces:
    - name: source
  steps:
    - name: flake8
      image: python:3.11-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        set -e
        python -m pip install --upgrade pip
        pip install flake8
        flake8 --max-line-length=120 .
